application: dr-shortener
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  login: admin
  auth_fail_action: redirect
  static_dir: static

- url: /blog/admin/.*
  login: admin
  auth_fail_action: redirect
  script: _go_app
- url: /blog/.*
  script: _go_app
- url: /shortener/admin/.*
  login: admin
  auth_fail_action: redirect
  script: _go_app
- url: /bookmark/admin/.*
  script: _go_app
- url: /bookmark/.*
  script: _go_app
